import React from 'react';
import { ArrowLeft, FileCheck } from 'lucide-react';
import { useSubSentry } from '../context/SubSentryContext';

export const TermsPage: React.FC = () => {
  const { setCurrentRoute } = useSubSentry();

  return (
    <div className="min-h-screen bg-canvas text-primary antialiased font-sans p-6 sm:p-10 max-w-3xl mx-auto">
      <div className="mb-8">
        <button
          onClick={() => setCurrentRoute('/signin')}
          className="inline-flex items-center gap-1.5 text-xs text-secondary hover:text-primary transition-colors mb-6 focus:outline-hidden"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to SubSentry</span>
        </button>

        <div className="flex items-center gap-2.5 text-accent mb-2">
          <FileCheck className="w-5 h-5" />
          <span className="text-xs font-semibold uppercase tracking-wider">User Agreement</span>
        </div>
        <h1 className="text-2xl font-bold tracking-tight text-primary">
          Terms of Service
        </h1>
        <p className="text-xs text-secondary mt-1">
          Last revised: September 2026
        </p>
      </div>

      <div className="bg-surface border border-border rounded-lg p-6 sm:p-8 space-y-6 text-xs leading-relaxed text-secondary">
        <div>
          <h2 className="text-sm font-semibold text-primary mb-2">
            1. Service Description
          </h2>
          <p>
            SubSentry provides mathematical pattern analysis and recurrence detection across statement transactions. The analysis and confidence scores generated by the application serve as informational tools to assist users in managing recurring expenditures.
          </p>
        </div>

        <div className="border-t border-border/70 pt-6">
          <h2 className="text-sm font-semibold text-primary mb-2">
            2. Informational Purpose Only
          </h2>
          <p>
            SubSentry does not provide formal financial advisory, legal, or accounting services. Decisions regarding subscription cancellations, contract disputes, or merchant negotiations remain the sole responsibility of the user.
          </p>
        </div>

        <div className="border-t border-border/70 pt-6">
          <h2 className="text-sm font-semibold text-primary mb-2">
            3. User Responsibilities
          </h2>
          <p>
            Users are responsible for safeguarding account access and ensuring that uploaded statement data complies with applicable corporate and personal security policies.
          </p>
        </div>
      </div>
    </div>
  );
};
